config/routes.rb
Rails.application.routes.draw do
  resources :items

  root 'items#index'

  resources :items do
    collection do
      post :import_csv
    end

    member { get :image }
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  acts_as_copy_target

  def self.to_csv
    CSV.generate(headers: column_names, write_headers: true, force_quotes: true) do |csv|
      all.each do |row|
        csv << row.attributes.values_at(*column_names).map{|v| v.to_s.encode('utf-8', 'binary', invalid: :replace, undef: :replace, replace: '')}
      end
    end
  end

  def self.import_csv(csv_file)
    csv_text = csv_file.read

    CSV.parse(Kconv.toutf8(csv_text)) do |row|

    user = Item.new(row[0] )
    user.name         =  #csvの1列目を格納
    user.created_at   = row[1]  #csvの2列目を格納
    user.updated_at = row[2]  #csvの3列目を格納
    user.image     = row[3]  #csvの4列目を格納
    user.image_content_type = row[2]  #csvの3列目を格納

    user.save
  end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :image]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    respond_to do |format|
      format.html
      format.csv do
        File.open('items.csv', 'w') do |f|
          Item.copy_to do |line|
            f.write line
          end
        end
        send_file 'items.csv'
      end
    end
  end

  def import_csv
    Item.delete_all
    if Item.copy_from(params[:file].path)
      redirect_to items_path, :notice => "CSVファイルの読み込みに成功しました"
    else
      redirect_to items_path, :notice => "CSVファイルの読み込みに失敗しました。"
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.image = params[:item][:image].read
    @item.image_content_type = params[:item][:image].content_type

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def image
    send_data(@item.image, type: @item.image_content_type, disposition: :inline)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.haml
= form_for(@item) do |f|
  - if @item.errors.any?
    #error_explanation
      %h2
        = pluralize(@item.errors.count, "error")
        prohibited this item from being saved:
      %ul
        - @item.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :image
    %br/
    = f.file_field :image
  .actions
    = f.submit

app/views/items/edit.html.haml
%h1 Editing Item
= render 'form'
= link_to 'Show', @item
|
\#{link_to 'Back', items_path}

app/views/items/index.html.haml
%p#notice= notice
%h1 Listing Items
= link_to 'CSV形式でダウンロード', items_path(format: "csv")
= form_tag import_csv_items_path, multipart: true do
  = file_field_tag :file
  = submit_tag "Import"
%table
  %thead
    %tr
      %th Name
      %th Image
      %th{:colspan => "3"}
  %tbody
    - @items.each do |item|
      %tr
        %td= item.name
        %td=image_tag image_item_path(item)
        %td= link_to 'Show', item
        %td= link_to 'Edit', edit_item_path(item)
        %td= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Item', new_item_path

app/views/items/new.html.haml
%h1 New Item
= render 'form'
= link_to 'Back', items_path

app/views/items/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @item.name
%p
  %strong Image:
  =image_tag image_item_path(@item)
= link_to 'Edit', edit_item_path(@item)
|
\#{link_to 'Back', items_path}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Upman
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield